services:
  backend:
    container_name: adverly-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    container_name: adverly-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend
    volumes:
      - frontend_data:/app # Use a named volume instead of a bind mount
    environment:
      - NODE_ENV=production
      - PORT=8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://frontend:8081"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["npm", "run", "start"]
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .git/
volumes:
  frontend_data:
